export type CoverageStatus = 'ready' | 'mvp' | 'gap';

export type AppIdeaCoverage = {
  area: string;
  idea: string;
  routes: string[];
  capability: 'image' | 'video' | 'audio' | '3d' | 'llm' | 'workflow' | 'mixed';
  status: CoverageStatus;
  evidence: string;
  next: string;
};

export const appIdeasCoverage: AppIdeaCoverage[] = [
  {
    area: '音频',
    idea: 'AI 播客工厂',
    routes: ['/podcast'],
    capability: 'mixed',
    status: 'ready',
    evidence: '文本/图片输入、LLM 改稿、SeedAudio 生成、浏览器合成社媒视频入口已实现。',
    next: '登录态下继续做真实生成回归样例集。',
  },
  {
    area: '音频',
    idea: 'AI 有声书 / 网文听书工厂',
    routes: ['/audiobook'],
    capability: 'audio',
    status: 'ready',
    evidence: '长文输入、语言选择、TTS 任务提交与下载流程已接入。',
    next: '补章节拆分、批量任务和多角色旁白。',
  },
  {
    area: '音频',
    idea: '多人对话广播剧 / 互动音频短剧',
    routes: ['/audio-drama'],
    capability: 'audio',
    status: 'ready',
    evidence: '角色冲突输入、脚本生成、音频生成入口已实现。',
    next: '补可视化分轨和角色音色管理。',
  },
  {
    area: '音频',
    idea: 'AI 音乐 / 主题曲 / 情绪配乐 / 音效包',
    routes: ['/soundscape'],
    capability: 'audio',
    status: 'ready',
    evidence: '音乐音效工作台已拆分循环 BGM、音效包、氛围音、片头主题曲，并支持时长、无缝循环、无 vocals、商用授权、版权规避、交付清单和 JSON 导出。',
    next: '补批量变体生成和响度/波形分析。',
  },
  {
    area: '音频',
    idea: '儿童睡前故事',
    routes: ['/bedtime-story'],
    capability: 'audio',
    status: 'ready',
    evidence: '儿童安全故事生成、旁白音频、家长声音采样预览、监护关系、声音授权确认、隐私/惊吓内容约束、交付清单和 JSON 导出已实现。',
    next: '待接入已验证支持参考音频克隆的模型后，将采样直接用于定制音色。',
  },
  {
    area: '音频',
    idea: 'AI 名人/角色配音 meme & faceless 频道',
    routes: ['/voice-meme', '/faceless-channel'],
    capability: 'audio',
    status: 'ready',
    evidence: '原创角色 meme 与 faceless 频道音频工作台已支持原创/授权角色模式、权利方记录、授权确认、未授权真实人物拟声禁用、商用安全提示、发布清单和 JSON 导出。',
    next: '补企业级授权声线库和发布前自动审听。',
  },
  {
    area: '音频',
    idea: '冥想 / ASMR / 助眠白噪音',
    routes: ['/meditation'],
    capability: 'audio',
    status: 'ready',
    evidence: '冥想、ASMR、助眠音频描述生成入口已实现。',
    next: '补循环时长、淡入淡出和专辑封面。',
  },
  {
    area: '音频',
    idea: '实时语音 Agent / AI 客服 / IVR',
    routes: ['/voice-agent', '/avatar-agent'],
    capability: 'mixed',
    status: 'ready',
    evidence: 'voice-agent 已支持业务知识库、用户问题、LLM 客服回答和 SeedAudio 语音合成；avatar-agent 已支持电话/网页/门店/直播 IVR 预设、意图菜单、DTMF、隐私录音提示、转人工规则和 IVR JSON。',
    next: '真实电话/SIP、实时流式语音和工单转人工仍需外部服务闭环。',
  },
  {
    area: '3D',
    idea: '照片到实体手办工坊',
    routes: ['/figurine-3d', '/image-to-3d', '/stl-marketplace', '/pod-kit', '/pod-order'],
    capability: '3d',
    status: 'ready',
    evidence: '手办工坊已支持照片到 3D 生成、实体生产订单、目标高度、材质、底座文字、肖像授权、打印前人工质检、生产检查清单、STL/AR 后续路径和 JSON 导出。',
    next: '真实支付、物流和供应商下单 API 待接入。',
  },
  {
    area: '3D',
    idea: '游戏/元宇宙 UGC 资产工厂',
    routes: ['/game-asset-3d', '/game-sprite'],
    capability: 'mixed',
    status: 'ready',
    evidence: '游戏资产工作台已支持 Roblox/Unity/Unreal 预设、资产类型、Rig 目标、PBR、面数、生成模式、LOD/碰撞/贴图质检、2D 精灵图配套入口和 JSON 交付清单。',
    next: '补真实自动 rigging、引擎导入校验和在线 3D 预览。',
  },
  {
    area: '3D',
    idea: 'AR 电商试摆 / USDZ 上架',
    routes: ['/ar-commerce', '/image-to-3d', '/text-to-3d'],
    capability: '3d',
    status: 'ready',
    evidence: 'AR 商品工作台已支持 GLB/USDZ URL、真实尺寸校准、model-viewer/Quick Look 嵌入代码、平台预设、加载体积检查、移动端兼容和转化追踪清单。',
    next: '补服务端 USDZ 自动转换和真实 3D 在线预览。',
  },
  {
    area: '3D',
    idea: '宠物/亲人 3D 公仔纪念摆件',
    routes: ['/memorial-figurine', '/image-to-3d', '/stl-marketplace', '/pod-order'],
    capability: '3d',
    status: 'ready',
    evidence: '纪念公仔页已支持宠物/亲人授权照片到 3D 模型、纪念底座、目标尺寸、材质、生产检查、壁厚/水密/支撑后续检查路径和生产 JSON。',
    next: '真实网格自动检测和供应商生产状态回传待接入。',
  },
  {
    area: '3D',
    idea: '文字/照片到 3D 打印电商模型市集',
    routes: ['/stl-marketplace', '/text-to-3d', '/image-to-3d'],
    capability: '3d',
    status: 'ready',
    evidence: 'STL 市集工作台已支持免费预览、付费 STL、代打印档位、授权类型、售价/平台费/创作者分成、壁厚/水密/支撑/商业授权质检、上架文案和 JSON 导出。',
    next: '补真实 STL 网格分析、文件托管和支付结算。',
  },
  {
    area: '连续内容',
    idea: 'AI 短剧账号量产工厂',
    routes: ['/showrunner', '/short-drama', '/account-matrix'],
    capability: 'mixed',
    status: 'ready',
    evidence: 'Showrunner 连续内容台已支持角色圣经、参考图资产、分集队列、镜头提示词、角色一致性锁定、审片清单，并可串联短剧生成和账号矩阵排产。',
    next: '补真实多集批量渲染队列和跨集角色一致性评分。',
  },
  {
    area: '连续内容',
    idea: '虚拟偶像 / AI 网红',
    routes: ['/virtual-influencer'],
    capability: 'video',
    status: 'ready',
    evidence: '角色参考图到 vlog/广告/舞蹈短片入口已实现。',
    next: '补人设库和连续记忆。',
  },
  {
    area: '连续内容',
    idea: '连载动态漫 / AI 条漫工作室',
    routes: ['/dynamic-comic'],
    capability: 'video',
    status: 'ready',
    evidence: '分镜/角色参考到动态漫画视频入口已实现。',
    next: '补漫画分页导入和台词气泡导出。',
  },
  {
    area: '连续内容',
    idea: 'AI 网剧 / Showrunner',
    routes: ['/showrunner'],
    capability: 'llm',
    status: 'ready',
    evidence: 'Showrunner 工作台已支持项目设定、类型预设、角色圣经、参考资产、分集生产队列、每集镜头结构、视频提示词和项目 JSON 导出。',
    next: '补真实视频生成队列状态回传和成片归档。',
  },
  {
    area: '连续内容',
    idea: '系列品牌广告 / 连续剧情带货',
    routes: ['/brand-campaign'],
    capability: 'video',
    status: 'ready',
    evidence: '品牌/产品/角色参考到连续广告短片入口已实现。',
    next: '补多版本投放报表。',
  },
  {
    area: '连续内容',
    idea: '儿童动画连载 / 个性化睡前故事剧',
    routes: ['/child-animation', '/kids-book', '/bedtime-story'],
    capability: 'mixed',
    status: 'ready',
    evidence: '儿童连载入口已支持监护关系、儿童昵称、肖像授权、儿童安全内容、隐私限制、分集计划 JSON，并串联儿童动画、绘本插画和睡前故事音频。',
    next: '补真实系列绘本排版和多集生成状态回传。',
  },
  {
    area: '带声视频',
    idea: '病毒特效模板工厂',
    routes: ['/viral-video'],
    capability: 'video',
    status: 'ready',
    evidence: '参考图到病毒特效短视频入口已实现。',
    next: '沉淀模板库和热榜排序。',
  },
  {
    area: '带声视频',
    idea: '一句话 / 一张图出带声电影级短片',
    routes: ['/cinematic-video'],
    capability: 'video',
    status: 'ready',
    evidence: '参考图到原生带声电影短片入口已实现。',
    next: '补文本直出视频模式。',
  },
  {
    area: '带声视频',
    idea: '歌曲秒变对口型 MV / 会唱歌的脸',
    routes: ['/music-video'],
    capability: 'video',
    status: 'ready',
    evidence: '图片+歌曲到对口型 MV 入口已实现。',
    next: '补歌词字幕和节拍点预览。',
  },
  {
    area: '带声视频',
    idea: '带对白 Meme / Brainrot',
    routes: ['/meme-video', '/talking-pet'],
    capability: 'video',
    status: 'ready',
    evidence: '参考图说话 meme 和宠物/名画开口视频入口已实现。',
    next: '补字幕样式和梗图模板。',
  },
  {
    area: '带声视频',
    idea: '复活亲人 / 拥抱重逢',
    routes: ['/hug-video', '/old-photo-live', '/family-photo-live'],
    capability: 'video',
    status: 'ready',
    evidence: '拥抱、老照片开口和全家福动起来页面均加入授权与发布安全外壳，支持授权确认、AI 标注、温和克制、不冒充真实发言、风险提示和授权 JSON。',
    next: '真实身份/亲属关系审核和人工复核队列待接入。',
  },
  {
    area: '人像',
    idea: 'AI 职业头像',
    routes: ['/headshot'],
    capability: 'image',
    status: 'ready',
    evidence: '自拍到职业头像入口已实现。',
    next: '补批量套装和 LinkedIn 规格导出。',
  },
  {
    area: '人像',
    idea: 'AI 证件照',
    routes: ['/id-photo'],
    capability: 'image',
    status: 'ready',
    evidence: '自拍到白底证件照风格入口已实现。',
    next: '补国家规格裁切和合规检查。',
  },
  {
    area: '人像',
    idea: '婚纱 / 古风 / 旅拍写真',
    routes: ['/wedding', '/wedding-trailer'],
    capability: 'mixed',
    status: 'ready',
    evidence: '婚纱写真图和婚礼预告片入口已实现。',
    next: '补套系打包。',
  },
  {
    area: '人像',
    idea: 'AI 约会资料照优化',
    routes: ['/dating-photo'],
    capability: 'image',
    status: 'ready',
    evidence: '自拍到真实约会头像入口已实现。',
    next: '补平台比例和安全提示。',
  },
  {
    area: '人像',
    idea: '未来宝宝 + Baby Podcast',
    routes: ['/future-baby', '/baby-podcast'],
    capability: 'mixed',
    status: 'ready',
    evidence: '未来宝宝图片和 baby podcast 视频入口已实现。',
    next: '补娱乐用途标识。',
  },
  {
    area: '人像',
    idea: 'AI 时光机 / 变老变年轻 / 抱抱童年自己',
    routes: ['/time-machine', '/hug-video'],
    capability: 'mixed',
    status: 'ready',
    evidence: '时光机肖像和拥抱重逢视频入口已实现。',
    next: '补童年合成场景专用预设。',
  },
  {
    area: '人像',
    idea: 'AI Yearbook / 复古穿越写真',
    routes: ['/yearbook', '/past-life', '/art-portrait'],
    capability: 'image',
    status: 'ready',
    evidence: '年鉴、前世写真、名画肖像入口已实现。',
    next: '补风格包下载。',
  },
  {
    area: '人像',
    idea: '线下影楼降维打击',
    routes: ['/photo-studio-suite'],
    capability: 'workflow',
    status: 'ready',
    evidence: '影楼工作台已支持职业照、证件照、婚纱、年鉴、约会照套餐，多图上传预览、客户订单、隐私授权、人工复核、重修规则、交付文件名和订单 JSON。',
    next: '补真实客户相册存储、修片状态流转和门店收银。',
  },
  {
    area: '情感视频',
    idea: '拥抱/亲吻重逢',
    routes: ['/hug-video'],
    capability: 'video',
    status: 'ready',
    evidence: '多参考图到拥抱重逢短片入口已实现。',
    next: '亲吻类场景需加入更严格同意提示。',
  },
  {
    area: '情感视频',
    idea: '抱抱童年的自己 / 未来的自己',
    routes: ['/hug-video', '/time-machine'],
    capability: 'mixed',
    status: 'ready',
    evidence: '时光机可生成童年/未来版本参考图，拥抱视频页已内置童年自己案例，并加入授权、安全表达、AI 标注和不冒充真实发言清单。',
    next: '补专门的自我对话脚本模板和多年龄段自动串联。',
  },
  {
    area: '情感视频',
    idea: '老照片修复上色 + 全家福动起来',
    routes: ['/photo-restore', '/family-photo-live'],
    capability: 'mixed',
    status: 'ready',
    evidence: '老照片修复和全家福动起来入口已实现。',
    next: '补批量相册工作流。',
  },
  {
    area: '情感视频',
    idea: '会开口说话的老照片 / 逝者留言',
    routes: ['/old-photo-live', '/talking-photo'],
    capability: 'video',
    status: 'ready',
    evidence: '老照片开口和会说话照片页已支持图片+音频口型视频，并加入纪念用途授权、AI 标注、温和克制、不伪造真实发言、风险提示和授权 JSON。',
    next: '补真实亲属授权审核和脚本敏感内容复核。',
  },
  {
    area: '情感视频',
    idea: '会说话/唱歌的宠物 & 名画',
    routes: ['/talking-pet'],
    capability: 'video',
    status: 'ready',
    evidence: '宠物/名画图片+音频到开口视频入口已实现。',
    next: '补一键生成配音到视频链路。',
  },
  {
    area: '社交 UGC',
    idea: 'AI 算命看相 / 前世今生',
    routes: ['/fortune', '/past-life'],
    capability: 'mixed',
    status: 'ready',
    evidence: '娱乐报告和前世写真入口已实现。',
    next: '补分享卡片。',
  },
  {
    area: '社交 UGC',
    idea: 'AI 表情包 / Meme 工厂',
    routes: ['/sticker-meme', '/meme-video'],
    capability: 'mixed',
    status: 'ready',
    evidence: '贴纸图和说话 meme 视频入口已实现。',
    next: '补贴纸包批量导出。',
  },
  {
    area: '社交 UGC',
    idea: 'AI 情侣合成视频',
    routes: ['/couple-photo', '/couple-video', '/hug-video'],
    capability: 'mixed',
    status: 'ready',
    evidence: '情侣合照、合体视频和拥抱短片入口已实现。',
    next: '补纪念日模板。',
  },
  {
    area: '社交 UGC',
    idea: '穿越名画 / 变身名画人物',
    routes: ['/art-portrait'],
    capability: 'image',
    status: 'ready',
    evidence: '自拍到名画肖像入口已实现。',
    next: '补更多艺术风格。',
  },
  {
    area: '社交 UGC',
    idea: '动漫变身',
    routes: ['/anime-transform'],
    capability: 'image',
    status: 'ready',
    evidence: '自拍到动漫手绘肖像入口已实现。',
    next: '补风格矩阵。',
  },
  {
    area: '社交 UGC',
    idea: 'Looksmax 颜值扫描',
    routes: ['/looksmax'],
    capability: 'image',
    status: 'ready',
    evidence: '自拍到自然 glow-up 视觉入口已实现。',
    next: '补非医疗化评分说明。',
  },
  {
    area: '社交 UGC',
    idea: '宠物拟人 / 公仔 / 会说话毛孩子',
    routes: ['/pet-human', '/pet-portrait', '/talking-pet', '/figurine-3d'],
    capability: 'mixed',
    status: 'ready',
    evidence: '宠物拟人、肖像、说话视频和 3D 手办入口已实现。',
    next: '补宠物主题首页组合包。',
  },
  {
    area: '电商',
    idea: 'AI 商拍虚拟模特 + 商品广告视频',
    routes: ['/ecommerce-suite', '/product-photo', '/amazon-listing', '/virtual-try-on', '/virtual-model-ad', '/ugc-ad-factory', '/social-publisher'],
    capability: 'mixed',
    status: 'ready',
    evidence: '电商创意套件已升级为总控流水线，支持商品图/示例图、SKU brief、卖点/合规限制、白底主图、生活方式图、A+ 图、试穿/模特图、广告短视频、Amazon listing、社媒发布包、QA 清单和 JSON 导出，同时保留分散单点入口。',
    next: '补 SKU 批量处理和跨步骤自动队列。',
  },
  {
    area: '电商',
    idea: '一键 AI 试衣间',
    routes: ['/virtual-try-on'],
    capability: 'image',
    status: 'ready',
    evidence: '人物+服装图到试衣结果入口已实现。',
    next: '补尺码/版型提示。',
  },
  {
    area: '电商',
    idea: '珠宝真人上身试戴',
    routes: ['/jewelry-try-on'],
    capability: 'image',
    status: 'ready',
    evidence: '人/手+珠宝到试戴图入口已实现。',
    next: '补材质和比例校验。',
  },
  {
    area: '电商',
    idea: '房产/家居虚拟布置',
    routes: ['/virtual-staging', '/home-renovation', '/real-estate-suite'],
    capability: 'mixed',
    status: 'ready',
    evidence: '虚拟布置、装修可视化和房产装修套件入口已实现。',
    next: '补户型批量导入。',
  },
  {
    area: '电商',
    idea: '菜品图 + 诱人动效',
    routes: ['/food-photo', '/food-video', '/ar-menu'],
    capability: 'mixed',
    status: 'ready',
    evidence: '菜品图、菜品视频、AR 菜单方案入口已实现。',
    next: '补菜单批量导入。',
  },
  {
    area: '电商',
    idea: '亚马逊主图/A+ 内容',
    routes: ['/amazon-listing'],
    capability: 'image',
    status: 'ready',
    evidence: '平台合规主图和 A+ 图入口已实现。',
    next: '补平台规则检查器。',
  },
  {
    area: '电商',
    idea: 'AI 美妆试妆',
    routes: ['/makeup'],
    capability: 'image',
    status: 'ready',
    evidence: '人物图到专业妆容入口已实现。',
    next: '补品牌色号映射。',
  },
  {
    area: '创作者',
    idea: 'AI UGC 带货口播视频工厂',
    routes: ['/ugc-ad-factory', '/sales-video', '/product-photo', '/social-publisher'],
    capability: 'mixed',
    status: 'ready',
    evidence: 'UGC 带货工厂已支持商品链接、商品图、目标人群、可证明卖点、平台预设、变体数量、合规开关、口播脚本矩阵、素材提示词、发布路径和 JSON 导出。',
    next: '补真实 URL 抓取、素材自动解析和成片任务队列。',
  },
  {
    area: '创作者',
    idea: 'YouTube 缩略图 / 小红书封面',
    routes: ['/thumbnail'],
    capability: 'image',
    status: 'ready',
    evidence: '提示词到高点击率封面图入口已实现。',
    next: '补平台尺寸预设。',
  },
  {
    area: '创作者',
    idea: 'AI 漫画 / 条漫到动态短剧',
    routes: ['/storyboard', '/dynamic-comic'],
    capability: 'mixed',
    status: 'ready',
    evidence: '分镜图和动态漫画视频入口已实现。',
    next: '补漫画页导入。',
  },
  {
    area: '创作者',
    idea: 'AI 视频翻译 / 对口型出海',
    routes: ['/video-translate'],
    capability: 'video',
    status: 'ready',
    evidence: '视频翻译页已支持转写/SRT 输入、目标语言、受众平台、语气、术语限制，输出本地化字幕、配音稿、标题、QA 清单，并支持 SRT/JSON 导出，可作为对口型出海的可运行前置包。',
    next: '真实 ASR、TTS、口型同步流水线仍需拆成多步服务。',
  },
  {
    area: '创作者',
    idea: 'AI 虚拟主播 / 24 小时直播带货',
    routes: ['/live-room', '/virtual-influencer'],
    capability: 'workflow',
    status: 'ready',
    evidence: '数字人直播间已支持渠道预设、商品卖点、主播人设、24 小时循环、FAQ 机器人、AI 标识、禁未证实承诺、转人工规则、运营 runbook 和 JSON 导出。',
    next: '补真实推流网关、弹幕监听和直播数据回传。',
  },
  {
    area: '创作者',
    idea: 'AI 分镜 / Storyboard 工作台',
    routes: ['/storyboard'],
    capability: 'image',
    status: 'ready',
    evidence: '脚本到分镜概念图入口已实现。',
    next: '补镜头表 CSV 导出。',
  },
  {
    area: '视频后期',
    idea: '爆款视频续命 / video extend',
    routes: ['/video-extend'],
    capability: 'video',
    status: 'ready',
    evidence: '视频续写入口已实现。',
    next: '补首尾帧控制。',
  },
  {
    area: '视频后期',
    idea: '一句话改视频 / 对话式视频编辑',
    routes: ['/video-edit'],
    capability: 'video',
    status: 'ready',
    evidence: '上传视频和编辑指令入口已实现。',
    next: '补多轮编辑历史。',
  },
  {
    area: '视频后期',
    idea: '广告多版本 A/B 素材工厂',
    routes: ['/ad-variants'],
    capability: 'video',
    status: 'ready',
    evidence: '上传广告视频到 A/B 变体入口已实现。',
    next: '补批量版本管理。',
  },
  {
    area: '视频后期',
    idea: '视频换脸 / 换角色',
    routes: ['/video-faceswap'],
    capability: 'video',
    status: 'ready',
    evidence: '换角色工作台已支持源视频上传、目标角色参考图预览、授权确认、结构化生成指令、交付清单和视频编辑提交。',
    next: '待接入已验证支持目标参考图直接条件输入的换角色模型。',
  },
  {
    area: '视频后期',
    idea: '老视频超分修复',
    routes: ['/video-upscale'],
    capability: 'video',
    status: 'ready',
    evidence: '上传低清视频到 1080p 增强入口已实现。',
    next: '补预览对比。',
  },
  {
    area: '数字人',
    idea: 'AI 口播带货视频工厂',
    routes: ['/ugc-ad-factory', '/sales-video', '/virtual-model-ad'],
    capability: 'mixed',
    status: 'ready',
    evidence: 'UGC 工厂可从商品 URL、素材和卖点生成口播脚本矩阵及视频提示词，并串联 sales-video 与 virtual-model-ad 生成口播/模特广告素材。',
    next: '补从商品页自动抽取卖点到成片的服务端队列。',
  },
  {
    area: '数字人',
    idea: '7x24 AI 数字人直播间',
    routes: ['/live-room'],
    capability: 'workflow',
    status: 'ready',
    evidence: '直播间工作台已支持 7x24 讲解循环、渠道节奏、商品话术、FAQ 问答、AI 披露、转人工、禁未证实承诺和直播 runbook JSON。',
    next: '补真实推流、直播控制台和互动机器人接口。',
  },
  {
    area: '数字人',
    idea: 'AI 讲师课程 / 企业培训视频',
    routes: ['/course-video'],
    capability: 'video',
    status: 'ready',
    evidence: '讲师图+音频到课程视频入口已实现。',
    next: '补课件解析。',
  },
  {
    area: '数字人',
    idea: '实时对话数字人客服 / IVR',
    routes: ['/avatar-agent', '/voice-agent'],
    capability: 'mixed',
    status: 'ready',
    evidence: '数字人前台已支持电话 IVR、网页客服、门店屏和直播客服模式，能生成意图流程、知识库回答、DTMF 映射、隐私/录音提示、转人工策略，并串联语音客服生成回答音频。',
    next: '实时音视频会话和电话网关待接入。',
  },
  {
    area: '数字人',
    idea: '创作者视频翻译 / 多语言播报',
    routes: ['/video-translate'],
    capability: 'video',
    status: 'ready',
    evidence: 'video-translate 已支持多语言字幕、本地化标题、配音稿、受众平台、术语限制、QA 清单、SRT/JSON 导出，可作为创作者多语言播报交付包。',
    next: '补端到端 ASR、TTS 和口型同步。',
  },
  {
    area: '数字人',
    idea: '虚拟 KOL / 数字网红 IP 孵化',
    routes: ['/virtual-influencer', '/account-matrix'],
    capability: 'mixed',
    status: 'ready',
    evidence: '账号矩阵页已升级为虚拟 KOL/IP 日历，支持人设记忆、内容支柱、多账号、多天排产、品牌安全开关、视频提示词、virtual-influencer/social-publisher 交付路径和 JSON 导出。',
    next: '补真实跨账号发布状态、粉丝数据回流和长期记忆数据库。',
  },
  {
    area: '长尾 niche',
    idea: '纹身垂类',
    routes: ['/tattoo', '/tattoo-design'],
    capability: 'image',
    status: 'ready',
    evidence: '纹身设计和上身预览入口已实现。',
    next: '补部位尺寸预设。',
  },
  {
    area: '长尾 niche',
    idea: '宗教/信仰垂类',
    routes: ['/guardian-portrait'],
    capability: 'image',
    status: 'ready',
    evidence: '守护天使/信仰肖像入口已实现。',
    next: '补不同信仰风格安全提示。',
  },
  {
    area: '长尾 niche',
    idea: '纯组合创意玩法',
    routes: ['/combo-studio'],
    capability: 'workflow',
    status: 'ready',
    evidence: '组合工作流已支持商品带货、图文播客、3D 商品、短剧连载、虚拟主播等 pipeline preset，能串联图片、音频、视频、3D、LLM、发布应用路径，并导出执行说明和 JSON。',
    next: '补跨应用自动传参和批量任务队列。',
  },
  {
    area: '发布',
    idea: '社媒图片+音频展示与发布包',
    routes: ['/podcast', '/social-publisher'],
    capability: 'mixed',
    status: 'ready',
    evidence: '播客页支持浏览器合成竖版社媒视频；社媒发布包已支持多图和音频输入，生成图音转短视频方案、多平台标题、正文、标签、封面提示、发布检查清单并导出 JSON。',
    next: '真实平台一键发布需要 OAuth、平台 API 和审核队列。',
  },
];

export const coverageSummary = {
  total: appIdeasCoverage.length,
  ready: appIdeasCoverage.filter((item) => item.status === 'ready').length,
  mvp: appIdeasCoverage.filter((item) => item.status === 'mvp').length,
  gap: appIdeasCoverage.filter((item) => item.status === 'gap').length,
};
